import os
TOKEN = os.getenv('BOSTOBOT_TOKEN')
MYSQL_HOST = os.getenv('BOSTOBOT_MYSQL_HOST')
MYSQL_USER = os.getenv('BOSTOBOT_MYSQL_USER')
MYSQL_PASS = os.getenv('BOSTOBOT_MYSQL_PASS')
MYSQL_PORT = os.getenv('BOSTOBOT_MYSQL_PORT')
MYSQL_DATABASE = os.getenv('BOSTOBOT_MYSQL_DATABASE')
